### ISSUE TITLE
04-03 - GET /practice?mode=api

### ISSUE THREAD

**Issue by AbtaheeAli** [AbtaheeAli/assignments#15]
## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Create 2 endpoints, `/mumbling` and `/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [x] Create a new `webapi` api project
- [x] Create a endpoint for the `mumbling` endpoint
  - [x] Create a new Controller called `MumblingController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling(https://www.codewars.com/kata/mumbling) and return the result
  - [x] Have your code return the string
- [x] Create a endpoint for the `explosion` endpoint
  - [x] Create a new Controller called `ExplosionController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata
        [https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion) and return the result
  - [x] Have your code return the string

## Adventure Mode

None

## Epic Mode

None

## Resources

- Use [Insomnia](https://insomnia.rest/) for interacting with your API.

**Comment by AbtaheeAli** [comment]
https://github.com/AbtaheeAli/KatasAPI.git

**Comment by AbtaheeAli** [comment]
Your homework **04-03 - GET /practice?mode=api** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74dc376b990fefa4b57db26c0337e9d122b96fd7/giphy-16.gif)
> &ldquo;Well done!&rdquo;

**Comment by gstark** [comment]
Great work!
